### ISSUE TITLE
Add Microsoft Logo and Dapr Blog Case study

### ISSUE THREAD

**Issue by msfussell** [dapr/website#58]
It was suggested that a Microsoft Logo with a case study on the Dapr Blog about the use of Azure Container Apps and/or Azure Kubernetes Service is added. Then people visiting the site can see the MS logo and understand Micorosoft's contribution and commitment to Dapr. This is in the same vein as the Alibaba story

**Comment by marcduiker** [comment]
Closing since we have this now: https://dapr.io/enterprise/. If changes are required regarding the enterprise page, another issue can be created.
