### ISSUE TITLE
Proposal - October 2022 website refresh

### ISSUE THREAD

**Issue by paulyuk** [dapr/website#66]
Summary:
This tracks a website refresh to be reviewed by STC to improve user experience and increase clickthrough rates (CTR) to our top calls to action

Calls to action:
I believe our prioritized goals and CTAs are

- Get started [with Dapr CLI and quickstarts]
- Learn about Dapr features, technology, and case studies to gain confidence [via docs and deep links]
- Learn about the Dapr Community [the community around meetings, GH, discord and more is itself a feature]

Key challenges:

- Site does not have analytics for most links, so we are flying blind mostly around what users are clicking on or bouncing from #65 
- Testimonials links has very small CTR = 0.1%.  I believe Testimonials verbiage feels like marketing.  
- The hero of Dapr is the set of best practice APIs/building blocks, but this is too far below the fold
- We don't show code anywhere to attract real devs.  this still has a CTO or architect feel to it

Proposed changes:
- fix lack of telemetry.  PR #64 
-- design changes -- happy to A/B test--
- rename Testimonials to Case Studies (more like Kubernetes.io)
- Add a new tab for Community
- Remove topmost button for Get started in favor of one in the middle of page, making room for community
- move up the API and building block blurb
- Remove the noisy animation under "Build connected distributed applications faster"
- Consider adding a more prominent Case Studies teaser section that loops through logos + quotes.  Keep simple badges above the fold however.

**Comment by msfussell** [comment]
Completed for Oct
