### ISSUE TITLE
Add links and descriptions here for two new APIs: Configuration and Distributed lock

### ISSUE THREAD

**Issue by paulyuk** [dapr/website#67]
Add links and descriptions here for two new APIs.  Configuration and Distributed lock.  Clarify these are Alpha for now.
<img width="300" alt="image" src="https://user-images.githubusercontent.com/1968137/197305613-ddce347e-27c6-4b51-aaa8-bafceae488bc.png">

**Comment by marcduiker** [comment]
Configuration and Dist lock have been added with the new website design some months ago.
