### ISSUE TITLE
Set dapr/website repo to public

### ISSUE THREAD

**Issue by nate-double-u** [dapr/website#70]
As per conversations we've had: the website shouldn't be private, it should be open source.
- https://github.com/cncf/techdocs/issues/133#issuecomment-1268763515, https://github.com/cncf/techdocs/issues/133#issuecomment-1268776498
- https://lists.cncf.io/g/cncf-dapr-maintainers/topic/94125877#69

We can use this issue to list concerns/processes.

**Comment by msfussell** [comment]
Website repo is now public. Closing this issue.
