### ISSUE TITLE
Website navigation broken with Microsoft Edge browser 'Strict mode'

### ISSUE THREAD

**Issue by dbrattli** [dapr/website#74]
**Describe the bug**

The top navigation bar does not work with Microsoft Edge browser

**Steps to reproduce**
1. Go to https://dapr.io/
2. Click on 'Docs'

Nothing happens. Nothing happens if you click any other tabs like "Case Studies" or "Blog" either.

**Expected behavior**

Expect e.g the Docs page to be navigated to when clicked on. Currently I have to right click and select "Open link in new tab" to navigate to e.g Docs.

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro 22H2 (22621.900)
 - Browser: Microsoft Edge
 - Version: 108.0.1462.46 (Official build) (64-bit)

**Comment by laurentkempe** [comment]
I see the same issue

OS: Windows 11 Pro 22H2 (22621.1555)
Browser: Microsoft Edge
Version: 112.0.1722.48 (Official build) (64-bit)

**Comment by AaronCrawfis** [comment]
@laurentkempe @dbrattli thanks for reporting! Could you try something for me:

1. Attempt to click the Docs button, which should fail
2. Right click the Docs button and click Inspect
3. Paste screenshots for the Div for the `nav-item` and the console

Here's what I'm seeing on Edge (stable and dev) for Windows 11, where the buttons work as expected for me:

<img width="909" alt="image" src="https://user-images.githubusercontent.com/54363786/233681160-3cb9d89d-9fa2-40fc-8cea-e3d8d787da7e.png">
(first error is unrelated, will investigate)

<img width="584" alt="image" src="https://user-images.githubusercontent.com/54363786/233681620-edf7b9f8-f926-4481-9c8d-eee6f14abe90.png">


My guess is the `onClick` method may be causing some issues.

Thanks!

**Comment by laurentkempe** [comment]
Here is finally an answer to your question @AaronCrawfis now that I see your answer

![image](https://github.com/dapr/website/assets/272612/95257509-b656-432a-b286-8238854f27f1)

I have found the problem; I have strict mode set for tracking prevention and with Balanced mode it works

![image](https://github.com/dapr/website/assets/272612/8328ac0c-05b0-4e27-acb9-4b919ae1331f)

**Comment by GaTechThomas** [comment]
I use Strict mode in Edge, and the vast majority of sites have no problem at all. The state of privacy has become absolutely horrible, so switching to anything other than Strict is not ok. I'd like to help to fix this, but before I dig in it would be helpful to know whether anyone is already working on it or has suggestions on the fix.

**Comment by GaTechThomas** [comment]
Looking closer at the site, the links on dapr.io headers do not work. However, the links on docs.dapr.io do work just fine. 

For comparison, the GitHub link on the dapr.io looks like this:

<a class="nav-link" href="https://docs.dapr.io/?_gl=1*1kfqthr*_ga*Njc2MzMwNjE0LjE2OTAwODAxMDY.*_ga_60C6Q1ETC1*MTY5MDA4MDEwNS4xLjEuMTY5MDA4MjQzOS4wLjAuMA.." onclick="captureOutboundLink('https:\/\/docs.dapr.io\/'); return false;">Docs</a>

And the GitHub link on docs.dapr.io looks like this:

<a class="nav-link" href="https://github.com/dapr" target="_blank" rel="nofollow noopener noreferrer"><span>GitHub</span></a>

Why use google analytics on one site but not the other? Google is not doing so well at the "Don't Be Evil" thing. Until they've changed their ways I'd prefer to avoid them where possible. 

Said differently, is there a reason why we would need to keep google analytics on the main site? If it's not ok to remove it, then why is it ok to not have it on the docs site?

**Comment by AaronCrawfis** [comment]
Thanks for tracking this down to Strict mode and Google Analytics! We'll definitely work to get this fixed so if you have strict mode enabled we won't break links due to Google Analytics.

@greenie-msft would you be able to take a look?

**Comment by AaronCrawfis** [comment]
@GaTechThomas could you try visiting https://deploy-preview-79--daprio.netlify.app/ and seeing if the links work as expected?

**Comment by laurentkempe** [comment]
@AaronCrawfis I had a quick try and the issue seems to be resolved I could navigate to the Case Studies, Docs, Blog withotu any issue 👍🏼
