### ISSUE TITLE
[Urgent] Opt-out of "Automatically set up a basic Google Analytics 4 property"

### ISSUE THREAD

**Issue by chalin** [dapr/website#75]
In March (next week), Google will start creating new GA4 site tags if there's no existing GA4 ID connected to an existing UA ID. Dapr.io already has a GA4 site tag, it was setup via:

- #71 

While I have access to [dapr.io's UA console](https://analytics.google.com/analytics/web/#/a149338238w211841672p203359650/admin/ga4-setup-assistant), I don't have editor permissions. Could you grant me editor permissions, or have someone with editor permissions opt-out of "Automatically set up a basic Google Analytics 4 property" (click the checkbox shown by the arrow below):

> <img width="1350" alt="Screen Shot 2023-02-23 at 16 38 43" src="https://user-images.githubusercontent.com/4140793/221036632-d96cbee8-a128-4545-b071-da72241e4e1f.png">

For context regarding this problem, see:

- https://github.com/cncf/techdocs/issues/170

/cc @nate-double-u

**Comment by chalin** [comment]
To be clear, this opting out needs to be done for all three UA properties:

> <img width="357" alt="image" src="https://user-images.githubusercontent.com/4140793/221037231-16bd6e91-c156-407b-b366-382533d4dfd1.png">

**Comment by greenie-msft** [comment]
@chalin, I've updated the GA settings per your request. 

Also, would you like editor permissions? 

cc. @msfussell

**Comment by chalin** [comment]
Hi @greenie-msft, just to confirm that you've updated the settings for all three UA properties?
If so, in that case I don't need editor permissions, thanks!

**Comment by chalin** [comment]
Thanks!
